config/routes.rb
Messaging::Engine.routes.draw do
  resources :messages do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end
  post 'search' => 'messages#search'
  root :to => 'messages#index'
end

app/models/messaging/message.rb
module Messaging
  class Message
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming

    attr_accessor :recipients, :subject, :body, :conversation_id, :attachment

    validates :recipients, presence: true
    validates :subject, presence: true
    validates :body, presence: true

    def initialize(attributes = {})
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end

    def persisted?
      false
    end


    def recipients
      @recipient_list
    end

    def recipients=(string='')
      @recipient_list = []
      string.split(',').each do |s|
        @recipient_list << MessagingUser.find_by_email!(s.strip) unless s.blank?
      end
    end
  end
end

app/controllers/messaging/application_controller.rb
module Messaging
  class ApplicationController < ActionController::Base
    before_filter :authenticate_messaging_user!

    def current_user
      current_messaging_user
    end
  end
end

app/controllers/messaging/messages_controller.rb
module Messaging
  class MessagesController < Messaging::ApplicationController
    def index
      @box = params[:box] || 'inbox'
      @messages = current_user.mailbox.inbox if @box == 'inbox'
      @messages = current_user.mailbox.sentbox if @box == 'sent'
      @messages = current_user.mailbox.trash if @box == 'trash'
    end

    def new
      @message = Message.new
    end

    def create
      @message = Message.new params[:message]

      if @message.conversation_id
        @conversation = Conversation.find(@message.conversation_id)
        unless @conversation.is_participant?(current_user)
          flash[:alert] = "You do not have permission to view that conversation."
          return redirect_to root_path
        end
        receipt = current_user.reply_to_conversation(@conversation, @message.body, nil, true, true, @message.attachment)
      else
        unless @message.valid?
          return render :new
        end
        receipt = current_user.send_message(@message.recipients, @message.body, @message.subject, true, @message.attachment)
      end
      flash[:notice] = "Message sent."

      redirect_to message_path(receipt.conversation)
    end

    def show
      @conversation = Conversation.find_by_id(params[:id])
      unless @conversation.is_participant?(current_user)
        flash[:alert] = "You do not have permission to view that conversation."
        return redirect_to root_path
      end
      @message = Message.new conversation_id: @conversation.id
      current_user.read(@conversation)
    end

    def trash
      conversation = Conversation.find_by_id(params[:id])
      if conversation
        current_user.trash(conversation)
        flash[:notice] = "Message sent to trash."
      else
        conversations = Conversation.find(params[:conversations])
        conversations.each { |c| current_user.trash(c) }
        flash[:notice] = "Messages sent to trash."
      end
      redirect_to messages_path(box: params[:current_box])
    end

    def untrash
      conversation = Conversation.find(params[:id])
      current_user.untrash(conversation)
      flash[:notice] = "Message untrashed."
      redirect_to messages_path(box: 'inbox')
    end

    def search
      @search = params[:search]
      @messages = current_user.search_messages(@search)
      render :index
    end
  end
end

app/helpers/messaging/application_helper.rb
module Messaging
  module ApplicationHelper
  end
end

app/views/layouts/messaging/application.html.haml
!!!
%html
  %head
    %title Messaging
    %noscript
      = stylesheet_link_tag "messaging/mobile"
    :javascript
      // Edit to suit your needs.
      var ADAPT_CONFIG = {
        path: '#{request.protocol}#{request.host}:#{request.port}',
        dynamic: true,
        range: [
          '0px    to 760px  = #{asset_path('messaging/mobile.css')}',
          '760px  to 980px  = #{asset_path('messaging/720.css')}',
          '980px  to 1280px = #{asset_path('messaging/960.css')}',
          '1280px to 1600px = #{asset_path('messaging/1200.css')}',
          '1600px = #{asset_path('messaging/1560.css')}',
        ]
      };
    = stylesheet_link_tag "messaging/application"
    = javascript_include_tag "messaging/adapt"
    = javascript_include_tag "messaging/application"
    = csrf_meta_tags
  %body
    #wrapper
      %header
        .container_12
          .grid_12
            %h1 Messaging
            = link_to "Sign out", '/messaging_users/sign_out', method: :delete, class: 'sign-out'
      - if notice
        #notice
          .container_12
            .grid_12= notice
      - if alert
        #alert
          .container_12
            .grid_12= alert
      #content.container_12
        .grid_2
          %nav
            = link_to "Compose", new_message_path, class: 'compose'
            -if @box == 'inbox'
              = link_to "Inbox", messages_path(box: 'inbox'), class: 'selected'
            -else
              = link_to "Inbox", messages_path(box: 'inbox')
            -if @box == 'sent'
              = link_to "Sent", messages_path(box: 'sent'), class: 'selected'
            -else
              = link_to "Sent", messages_path(box: 'sent')
            -if @box == 'trash'
              = link_to "Trash", messages_path(box: 'trash'), class: 'selected'
            -else
              = link_to "Trash", messages_path(box: 'trash')
            = form_tag search_path do
              %input{ type: 'search', placeholder: 'Search', name: 'search' }
        #main.grid_10
          = yield
    #footer
      .container_12
        .grid_12
          =link_to "Rails Messaging", "http://github.com/frodefi/rails-messaging/"

app/views/messaging/messages/index.html.haml
- if @search
  %h2 Search results for '#{@search}'
- if @box == 'inbox'
  %h2 Inbox
- if @box == 'sent'
  %h2 Sent
- if @box == 'trash'
  %h2 Trash
= form_tag trash_messages_path, method: :delete do
  = hidden_field_tag 'current_box', @box
  %table#box
    %tr
      - unless @box == 'trash'
        %th
      %th Sender
      %th Subject
      %th Messages
      %th
    - @messages.each do |m|
      %tr{ class: "#{ 'unread' if m.is_unread?(current_messaging_user) }" }
        - unless @box == 'trash'
          %td= check_box_tag '', m.id, false, class: 'delete_multiple_checkbox', name: "conversations[]"
        %td= link_to m.last_sender, message_path(m)
        %td= link_to m.subject, message_path(m)
        %td= link_to m.count_messages, message_path(m)
        %td= link_to truncate(m.last_message.body), message_path(m)
  - unless @box == 'trash'
    = submit_tag "Delete checked messages", id: 'delete_multiple_button'

app/views/messaging/messages/new.html.haml
%h2 Compose
#compose
  = simple_form_for @message do |f|
    = f.label :recipients, required: false
    = f.input_field :recipients, data: { autocomplete_source: MessagingUser.all.map(&:name) }
    = f.label :subject, required: false
    = f.input_field :subject
    = f.label :body, required: false
    = f.input_field :body, as: :text
    = f.input :attachment, as: :file
    = f.button :submit, 'Send message'

app/views/messaging/messages/show.html.haml
#actions
  - if @conversation.is_trashed?(current_messaging_user)
    = link_to "Untrash", untrash_message_path(@conversation), class: :button, method: :post
  - else
    = link_to "Trash", trash_message_path(@conversation), class: :button, method: :delete
%h2.subject= @conversation.subject
%ul#conversation
  - @conversation.messages.each do |message|
    %li
      .head
        .from= message.sender
        .date #{message.created_at.to_s(:long)} (#{time_ago_in_words(message.created_at)} ago)
      .body= message.body
      - if message.attachment.url
        .attachment
          = link_to message.attachment_identifier, message.attachment.url
#reply
  = simple_form_for @message do |f|
    = f.input :conversation_id, as: :hidden
    = f.label :body, label: 'Reply', required: false
    = f.input_field :body, as: :text, label: 'Reply'
    = f.input :attachment, as: :file
    = f.button :submit, 'Reply to conversation'